project:
  type: website

website:
  title: "Career Evaluation Product - Group 6"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Project Overview
      - href: data_preparation.qmd
        text: Data Preparation
      - href: eda.qmd
        text: Exploratory Analysis
      - href: benchmark_analysis.qmd
        text: Benchmark Analysis
      - href: skill_gap_analysis.qmd
        text: Skill Gap Analysis
      - href: predictive_modeling.qmd
        text: Predictive Modeling

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
